#!/usr/bin/env python3
"""Generate `docs/STATUS.md` -- every number this repo states about itself.

A number written into prose is a second source for a fact a checker
already computes, and the second source rots (L16). So **no prose document in
this repo quotes a countable fact**: they link here, and this file is
generated. Everything in it is measured from the tree on every run.

What stays in prose is anything that is a *judgement*: what a directory is
for lives in `docs/PLAYER.md`, and why a check is not redundant lives beside
it in `verify_all.py`.

    python3 tools/status.py            # rewrite docs/STATUS.md
    python3 tools/status.py --check    # fail if it is out of date

`--check` is one of the checks in `verify_all.py`, so a commit that changes
the tree and not this document fails.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import verify_all
import verify_layers
import verify_port

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "web" / "src"
OUT = ROOT / "docs" / "STATUS.md"

#: Directory -> layer, **taken from the checker** rather than restated: a
#: generated document quoting its own copy of a table is the same fault as a
#: hand-written one quoting a count.
LAYER_OF = verify_layers.LAYER_OF


def src_files(d: Path) -> list[Path]:
    return sorted(p for p in d.rglob("*")
                  if p.suffix in (".ts", ".tsx") and p.is_file())


def tree_rows() -> list[tuple[str, int, int, str]]:
    rows = []
    for name, layer in LAYER_OF.items():
        d = SRC / name
        if not d.is_dir():
            continue
        files = src_files(d)
        lines = sum(len(p.read_text().splitlines()) for p in files)
        rows.append((name, lines, len(files), layer))
    return sorted(rows, key=lambda r: -r[1])


def largest(n: int) -> list[tuple[str, int]]:
    out = [(str(p.relative_to(SRC)), len(p.read_text().splitlines()))
           for p in src_files(SRC)]
    return sorted(out, key=lambda x: -x[1])[:n]


def interface_members(path: Path, name: str) -> int:
    """How many members an `export interface` declares.

    `PlayerCommands` against `PlayerView` is the player's standing measurement
    of how much of itself a click can reach.
    """
    src = path.read_text()
    m = re.search(r"export interface %s\b[^{]*\{" % re.escape(name), src)
    if not m:
        return 0
    i, depth, n = m.end(), 1, 0
    while depth and i < len(src):
        j = src.find("\n", i)
        if j < 0:
            break
        line, i = src[i:j], j + 1
        depth += line.count("{") - line.count("}")
        if depth >= 1 and re.match(
                r"\s*(?:readonly\s+)?[A-Za-z_][A-Za-z0-9_]*\s*[?(:]", line):
            n += 1
    return n


def tsv_rows(path: Path) -> int:
    return sum(1 for line in path.read_text().splitlines()
               if line and not line.startswith("#"))


def count_diverges() -> dict[str, int]:
    """Every declared departure, by directory of `web/src/`: every source
    file, in comments only, one per occurrence (`verify_port.marker_counts`).
    """
    return verify_port.marker_counts(verify_port.DIVERGES_TAG)


def count_open() -> dict[str, int]:
    """`[open]` markers: questions the port and the exporter are honest about
    not having answered. Together with the divergences, the two numbers that
    say how finished the transcription is. Measured as `count_diverges` is.
    """
    return verify_port.marker_counts(verify_port.OPEN_TAG)


def count_uncited() -> int:
    """The uncited-export count, measured the way `verify_port` measures it."""
    n = 0
    for path in verify_port.game_files():
        text = path.read_text()
        defined = {d for d, _ in verify_port.DEF.findall(text)}
        lines = text.splitlines()
        for i, line in enumerate(lines, 1):
            m = verify_port.EXPORT_FN.match(line)
            if not m or m.group(1) in defined:
                continue
            if verify_port.PORT_ONLY.search(
                    verify_port.comment_block(lines, i - 1)):
                continue
            n += 1
    return n


def render() -> str:
    named = verify_port.annotations()
    ported = verify_port.check_names(named)
    n_in, n_range, n_out = verify_port.coverage_counts(named, ported)
    n_cls, n_known, cov_pl, all_pl = verify_port.class_counts()
    rules = verify_layers.build_rules()
    ratchets = [r for r in rules.values() if r.severity == "ratchet"]
    rows = tree_rows()
    total_lines = sum(r[1] for r in rows)
    total_files = sum(r[2] for r in rows)
    uncited = count_uncited()

    L: list[str] = []
    add = L.append

    add("<!-- GENERATED by tools/status.py. Do not edit; run the tool. -->")
    add("# Status")
    add("")
    add("Every countable fact this repo states about itself, measured from the")
    add("tree. **Generated by `tools/status.py`; do not edit by hand.** No")
    add("other document quotes these numbers -- they link here, because a")
    add("number written twice is a number that will disagree with itself.")
    add("")
    add("`python3 tools/verify_all.py` checks that this file still matches the")
    add("tree, so a change that moves a number and does not regenerate fails.")
    add("")
    add("What is *not* here, on purpose: anything that is a judgement rather")
    add("than a measurement. What each directory is for is in")
    add("[`PLAYER.md`](PLAYER.md); what each check uniquely sees is in")
    add("`tools/verify_all.py`, beside the command that runs it.")
    add("")

    add("## The browser player, by directory")
    add("")
    add("| Directory | Lines | Files | Layer |")
    add("|---|---:|---:|---|")
    for name, lines, files, layer in rows:
        add(f"| `{name}/` | {lines} | {files} | {layer} |")
    add(f"| **total** | **{total_lines}** | **{total_files}** | |")
    add("")
    add("The largest files, which is where the pressure to split next is:")
    add("")
    for rel, n in largest(5):
        add(f"* `{rel}` — {n}")
    add("")

    add("## The port")
    add("")
    add("| | |")
    add("|---|---|")
    add(f"| Gameplay coverage | **{n_in} of {n_range}** annotated functions in "
        f"the gameplay address ranges have a port "
        f"({100 * n_in // max(1, n_range)}%) |")
    add(f"| Ported outside those ranges | {n_out} (opcodes, and the classes "
        f"whose handlers sit elsewhere) |")
    add(f"| Citations checked | {len(ported)} ported functions match "
        f"`functions.tsv` under the same name |")
    add(f"| Spawn classes | **{n_cls} of {n_known}** read classes have a "
        f"module, covering {cov_pl} of {all_pl} placements |")
    div, opn = count_diverges(), count_open()
    add(f"| Declared `[diverges]` | **{sum(div.values())}** — where the port "
        f"knowingly departs from the exe, each with its reason on the spot |")
    add(f"| `[open]` markers | **{sum(opn.values())}** — questions the port "
        f"and the exporter are honest about not having answered |")
    add("")
    add("Both markers are counted in **every** `.ts`/`.tsx` file under "
        "`web/src/`, one per occurrence, and only in comments — a word in "
        "code or in a string is not a marker (`verify_port.marker_lines`). "
        "Each departure and each question is written once, where it is "
        "made; everything that refers to it names it in words "
        "([`PLAYER.md`](PLAYER.md#one-departure-one-tag), "
        "\"One departure, one tag\"). By layer, from the same table as the "
        "directories above:")
    add("")
    add("| Layer | Directories | `[diverges]` | `[open]` |")
    add("|---|---|---:|---:|")
    layers: dict[str, list[str]] = {}
    for name, layer in LAYER_OF.items():
        if (SRC / name).is_dir():
            layers.setdefault(layer, []).append(name)
    for layer, names in layers.items():
        shown = ", ".join(f"`{n}/`" for n in names)
        add(f"| {layer} | {shown} | {sum(div.get(n, 0) for n in names)} | "
            f"{sum(opn.get(n, 0) for n in names)} |")
    # A marker in a directory `LAYER_OF` has not heard of is still counted
    # in the totals above; it gets a row of its own rather than vanishing
    # from this one.
    for n in sorted(k for k in set(div) | set(opn) if k not in LAYER_OF):
        add(f"| (no layer) | `{n}` | {div.get(n, 0)} | {opn.get(n, 0)} |")
    add("")
    n_cmd = interface_members(SRC / "app" / "commands.ts", "PlayerCommands")
    n_view = interface_members(SRC / "app" / "projection" / "player.ts",
                               "PlayerView")
    add(f"The two declared seams between the UI and the player: "
        f"**`PlayerCommands` has {n_cmd} members against `PlayerView`'s "
        f"{n_view}** — how much of the player a click can move, against how "
        f"much of it the page can see. Neither can grow without a line "
        f"appearing in the open.")
    add("")

    add("## The decomp")
    add("")
    add("| | |")
    add("|---|---|")
    add(f"| Named functions | {tsv_rows(ROOT / 'ghidra/annotations/functions.tsv')} "
        f"in `ghidra/annotations/functions.tsv` |")
    add(f"| Named globals | {tsv_rows(ROOT / 'ghidra/annotations/globals.tsv')} "
        f"in `ghidra/annotations/globals.tsv` |")
    add(f"| Checks | {len(verify_all.CHECKS)}, run together by "
        f"`tools/verify_all.py` (listed below) |")
    add("")

    add("## Ratchets")
    add("")
    add("A ratchet is a violation the architecture has not reached yet: a count")
    add("that may fall and may never rise. **Raising one is a decision for the")
    add("repository's owner, not a line edit in a checker**, and there is")
    add("deliberately no suppression comment.")
    add("")
    add("| Ratchet | Where | Now | Baseline |")
    add("|---|---|---:|---:|")
    add(f"| `uncited-exports` | `tools/verify_port.py` | {uncited} | "
        f"{verify_port.UNCITED_BASELINE} |")
    for r in ratchets:
        add(f"| `{r.name}` | `tools/verify_layers.py` | {len(r.hits)} | "
            f"{r.baseline} |")
    add("")
    if not ratchets:
        add(f"All {len(rules)} rules in `verify_layers.py` are `error` at zero;")
        add("a new violation of any of them fails the build rather than moving")
        add("a number. `uncited-exports` above is the only ratchet in the repo:")
        add("every exported function in `game/` should cite the exe function it")
        add("ports or declare itself `[port-only]`.")
        add("")

    add("## The checks")
    add("")
    add("Authored in `tools/verify_all.py` and rendered here, so there is one")
    add("list and not five. `python3 tools/verify_all.py` runs them all and")
    add("reports pass, fail and **skip** separately -- a check that asserted")
    add("nothing exits 3 and is never counted as green.")
    add("")
    add("| Check | What only it can see | Needs |")
    add("|---|---|---|")
    for c in verify_all.CHECKS:
        need = c.needs or "—"
        add(f"| `{c.name}` | {c.sees} | {need} |")
    add("")
    # Counted, not written down (L16).
    n_game = sum(1 for c in verify_all.CHECKS
                 if c.needs == verify_all.NEEDS_GAME)
    n_bundle = sum(1 for c in verify_all.CHECKS
                   if c.needs == verify_all.NEEDS_BUNDLE)
    add(f"{n_game} of them need the installed game and {n_bundle} need an "
        "exported")
    add("bundle. **That is a known hole, not a design:** a machine with")
    add("neither cannot run the checks that compare two histories, and a")
    add("bundle-free fixture is the open work that closes it.")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if docs/STATUS.md is out of date")
    args = ap.parse_args()

    text = render()
    if not args.check:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(ROOT)}")
        return 0

    if not OUT.exists():
        print(f"{OUT.relative_to(ROOT)} does not exist; "
              f"run `python3 tools/status.py`", file=sys.stderr)
        return 1
    if OUT.read_text() != text:
        import difflib
        old = OUT.read_text().splitlines()
        diff = list(difflib.unified_diff(old, text.splitlines(),
                                         "on disk", "measured", lineterm=""))
        print("\n".join(diff[:60]))
        print(f"\ndocs/STATUS.md is out of date -- "
              f"run `python3 tools/status.py`", file=sys.stderr)
        return 1
    print("docs/STATUS.md matches the tree")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
